[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.test]
verbosity = 2
gas_reports = ["*"]

[profile.ci]
verbosity = 3
fuzz_runs = 10000
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
