[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 10_000
via_ir = true

[profile.test]
verbosity = 2
gas_reports = ["*"]

[profile.ci]
verbosity = 3
fuzz_runs = 10000
gas_reports = ["*"]

[rpc_endpoints]
hyperliquid-testnet = "https://rpc.hyperliquid-testnet.xyz/evm"
hyperliquid = "https://rpc.hyperliquid.xyz/evm"

[etherscan]
hyperliquid = { key = "any", url = "https://sourcify.dev/server" }
hyperliquid-testnet = { key = "any", url = "https://sourcify.dev/server" }

# Verification settings
[profile.verify]
# Default verification provider to use if one is not specified
default_verification_provider = "sourcify"

# Verification provider common settings
[profile.verify.sourcify]
url = "https://sourcify.dev/server"

[profile.hyperliquid-testnet]
rpc_url = "${rpc_endpoints.hyperliquid-testnet}"

[profile.hyperliquid]
rpc_url = "${rpc_endpoints.hyperliquid}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
