[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 10_000
via_ir = true

[profile.test]
verbosity = 2
gas_reports = ["*"]

[profile.ci]
verbosity = 3
fuzz_runs = 10000
gas_reports = ["*"]

[rpc_endpoints]
hyperliquid-testnet = "https://rpc.hyperliquid-testnet.xyz/evm"
hyperliquid = "https://rpc.hyperliquid.xyz/evm"

[etherscan]
hyperliquid = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chainid = 999 }
hyperliquid-testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chainid = 998 }

[profile.hyperliquid-testnet]
rpc_url = "${rpc_endpoints.hyperliquid-testnet}"

[profile.hyperliquid]
rpc_url = "${rpc_endpoints.hyperliquid}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
